### ISSUE TITLE
Project chrisemunt/mg_php# Error when execute "make"

### ISSUE THREAD

**Issue by RRod72** [chrisemunt/mg_php#1]
Hi Team, 
Following the steps of the project readme https://github.com/chrisemunt/mg_php
1) install gcc (ready)
2) download the code from GitHub (ready)
3) We are located in the src directory of the project, and we execute phpize (ready)
4) We are located in the same directory and execute ./configure (ready)
5) then we execute make (to prepare the installation), and this is where we have several errors that do not let us continue. I imagine that due to some missing dependencies, I would not know which ones because they are not detailed as requirements either.
Could you help me about this errors when I execute "make"?
Attached screenshot with error
Thank you very much for your help

![Project chrisemunt_mg_php - Error execute MAKE](https://user-images.githubusercontent.com/81988842/113616680-ceaaeb00-962b-11eb-9294-5d1779c48ba6.jpeg)

**Comment by RRod72** [comment]
Hi, can someone help me with this issue?
Thank you very much for your help

**Comment by virtsevda** [comment]
This problem occurs on php 8.0 and higher.

**Comment by chrisemunt** [comment]
Support for PHP v8.x came out with mg_php v3.3.59.
